2021-07-19 16:39:10,212 ERROR 16072 nodejs.MongoNetworkError: failed to connect to server [undefined:27017] on first connect [Error: getaddrinfo ENOTFOUND undefined
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26) {
  name: 'MongoNetworkError'
}]
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26) {
  name: 'MongoNetworkError'
}]
    at Pool.<anonymous> (D:\Projects\llccing-demo\docker-node\docker-node-ngxin-mongo\node\node_modules\mongodb\lib\core\topologies\server.js:441:11)
    at Pool.emit (events.js:315:20)
    at D:\Projects\llccing-demo\docker-node\docker-node-ngxin-mongo\node\node_modules\mongodb\lib\core\connection\pool.js:564:14
    at D:\Projects\llccing-demo\docker-node\docker-node-ngxin-mongo\node\node_modules\mongodb\lib\core\connection\pool.js:999:11
    at D:\Projects\llccing-demo\docker-node\docker-node-ngxin-mongo\node\node_modules\mongodb\lib\core\connection\connect.js:32:7
    at callback (D:\Projects\llccing-demo\docker-node\docker-node-ngxin-mongo\node\node_modules\mongodb\lib\core\connection\connect.js:283:5)
    at Socket.<anonymous> (D:\Projects\llccing-demo\docker-node\docker-node-ngxin-mongo\node\node_modules\mongodb\lib\core\connection\connect.js:313:7)
    at Object.onceWrapper (events.js:422:26)
    at Socket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
name: "MongoNetworkError"
pid: 16072
hostname: LAPTOP-99LJL1ND

2021-07-19 16:47:38,066 ERROR 29048 nodejs.MongoNetworkError: failed to connect to server [127.0.0.1:27017] on first connect [MongoError: Authentication failed.
    at Connection.messageHandler (D:\Projects\llccing-demo\docker-node\docker-node-ngxin-mongo\node\node_modules\mongodb\lib\core\connection\connection.js:362:19)
    at Connection.emit (events.js:315:20)
    at processMessage (D:\Projects\llccing-demo\docker-node\docker-node-ngxin-mongo\node\node_modules\mongodb\lib\core\connection\connection.js:454:10)
    at Socket.<anonymous> (D:\Projects\llccing-demo\docker-node\docker-node-ngxin-mongo\node\node_modules\mongodb\lib\core\connection\connection.js:623:15)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23) {
  ok: 0,
  code: 18
}]
    at Connection.messageHandler (D:\Projects\llccing-demo\docker-node\docker-node-ngxin-mongo\node\node_modules\mongodb\lib\core\connection\connection.js:362:19)
    at Connection.emit (events.js:315:20)
    at processMessage (D:\Projects\llccing-demo\docker-node\docker-node-ngxin-mongo\node\node_modules\mongodb\lib\core\connection\connection.js:454:10)
    at Socket.<anonymous> (D:\Projects\llccing-demo\docker-node\docker-node-ngxin-mongo\node\node_modules\mongodb\lib\core\connection\connection.js:623:15)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23) {
  ok: 0,
  code: 18
}]
    at Pool.<anonymous> (D:\Projects\llccing-demo\docker-node\docker-node-ngxin-mongo\node\node_modules\mongodb\lib\core\topologies\server.js:441:11)
    at Pool.emit (events.js:315:20)
    at D:\Projects\llccing-demo\docker-node\docker-node-ngxin-mongo\node\node_modules\mongodb\lib\core\connection\pool.js:564:14
    at D:\Projects\llccing-demo\docker-node\docker-node-ngxin-mongo\node\node_modules\mongodb\lib\core\connection\pool.js:999:11
    at callback (D:\Projects\llccing-demo\docker-node\docker-node-ngxin-mongo\node\node_modules\mongodb\lib\core\connection\connect.js:75:5)
    at D:\Projects\llccing-demo\docker-node\docker-node-ngxin-mongo\node\node_modules\mongodb\lib\core\connection\connect.js:147:27
    at D:\Projects\llccing-demo\docker-node\docker-node-ngxin-mongo\node\node_modules\mongodb\lib\core\auth\scram.js:109:14
    at _callback (D:\Projects\llccing-demo\docker-node\docker-node-ngxin-mongo\node\node_modules\mongodb\lib\core\connection\connection.js:331:7)
    at Connection.messageHandler (D:\Projects\llccing-demo\docker-node\docker-node-ngxin-mongo\node\node_modules\mongodb\lib\core\connection\connection.js:362:9)
    at Connection.emit (events.js:315:20)
    at processMessage (D:\Projects\llccing-demo\docker-node\docker-node-ngxin-mongo\node\node_modules\mongodb\lib\core\connection\connection.js:454:10)
    at Socket.<anonymous> (D:\Projects\llccing-demo\docker-node\docker-node-ngxin-mongo\node\node_modules\mongodb\lib\core\connection\connection.js:623:15)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
name: "MongoNetworkError"
pid: 29048
hostname: LAPTOP-99LJL1ND

2021-07-19 16:48:56,622 ERROR 27676 nodejs.MongoError: Authentication failed.
    at MessageStream.messageHandler (D:\Projects\llccing-demo\docker-node\docker-node-ngxin-mongo\node\node_modules\mongodb\lib\cmap\connection.js:272:20)
    at MessageStream.emit (events.js:315:20)
    at processIncomingData (D:\Projects\llccing-demo\docker-node\docker-node-ngxin-mongo\node\node_modules\mongodb\lib\cmap\message_stream.js:144:12)
    at MessageStream._write (D:\Projects\llccing-demo\docker-node\docker-node-ngxin-mongo\node\node_modules\mongodb\lib\cmap\message_stream.js:42:5)
    at doWrite (_stream_writable.js:403:12)
    at writeOrBuffer (_stream_writable.js:387:5)
    at MessageStream.Writable.write (_stream_writable.js:318:11)
    at Socket.ondata (_stream_readable.js:717:22)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
ok: 0
code: 18
name: "MongoError"
pid: 27676
hostname: LAPTOP-99LJL1ND

2021-07-19 16:49:05,411 ERROR 9092 nodejs.MongoError: Authentication failed.
    at MessageStream.messageHandler (D:\Projects\llccing-demo\docker-node\docker-node-ngxin-mongo\node\node_modules\mongodb\lib\cmap\connection.js:272:20)
    at MessageStream.emit (events.js:315:20)
    at processIncomingData (D:\Projects\llccing-demo\docker-node\docker-node-ngxin-mongo\node\node_modules\mongodb\lib\cmap\message_stream.js:144:12)
    at MessageStream._write (D:\Projects\llccing-demo\docker-node\docker-node-ngxin-mongo\node\node_modules\mongodb\lib\cmap\message_stream.js:42:5)
    at doWrite (_stream_writable.js:403:12)
    at writeOrBuffer (_stream_writable.js:387:5)
    at MessageStream.Writable.write (_stream_writable.js:318:11)
    at Socket.ondata (_stream_readable.js:717:22)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
ok: 0
code: 18
name: "MongoError"
pid: 9092
hostname: LAPTOP-99LJL1ND

2021-07-19 09:32:47,005 ERROR 59 nodejs.MongooseServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017
    at NativeConnection.Connection.openUri (/app/node_modules/mongoose/lib/connection.js:846:32)
    at _mongoose._promiseOrCallback.cb (/app/node_modules/mongoose/lib/index.js:351:10)
    at Promise (/app/node_modules/mongoose/lib/helpers/promiseOrCallback.js:32:5)
    at new Promise (<anonymous>)
    at promiseOrCallback (/app/node_modules/mongoose/lib/helpers/promiseOrCallback.js:31:10)
    at Mongoose._promiseOrCallback (/app/node_modules/mongoose/lib/index.js:1149:10)
    at Mongoose.connect (/app/node_modules/mongoose/lib/index.js:350:20)
    at exports.connect (/app/app/database/init.js:14:14)
    at /app/app.js:9:5
    at Object.<anonymous> (/app/app.js:11:3)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
message: "connect ECONNREFUSED 127.0.0.1:27017"
reason: {"type":"Single","setName":null,"maxSetVersion":null,"maxElectionId":null,"servers":{},"stale":false,"compatible":true,"compatibilityError":null,"logicalSessionTimeoutMinutes":null,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"commonWireVersion":null}
pid: 59
hostname: 926f64e17392

2021-07-19 09:34:24,720 ERROR 58 nodejs.MongooseServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017
    at NativeConnection.Connection.openUri (/app/node_modules/mongoose/lib/connection.js:846:32)
    at _mongoose._promiseOrCallback.cb (/app/node_modules/mongoose/lib/index.js:351:10)
    at Promise (/app/node_modules/mongoose/lib/helpers/promiseOrCallback.js:32:5)
    at new Promise (<anonymous>)
    at promiseOrCallback (/app/node_modules/mongoose/lib/helpers/promiseOrCallback.js:31:10)
    at Mongoose._promiseOrCallback (/app/node_modules/mongoose/lib/index.js:1149:10)
    at Mongoose.connect (/app/node_modules/mongoose/lib/index.js:350:20)
    at exports.connect (/app/app/database/init.js:14:14)
    at /app/app.js:9:5
    at Object.<anonymous> (/app/app.js:11:3)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
message: "connect ECONNREFUSED 127.0.0.1:27017"
reason: {"type":"Single","setName":null,"maxSetVersion":null,"maxElectionId":null,"servers":{},"stale":false,"compatible":true,"compatibilityError":null,"logicalSessionTimeoutMinutes":null,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"commonWireVersion":null}
pid: 58
hostname: 3f4a6cb80e4d

2021-07-19 09:39:30,107 ERROR 59 nodejs.MongooseServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017
    at NativeConnection.Connection.openUri (/app/node_modules/mongoose/lib/connection.js:846:32)
    at _mongoose._promiseOrCallback.cb (/app/node_modules/mongoose/lib/index.js:351:10)
    at Promise (/app/node_modules/mongoose/lib/helpers/promiseOrCallback.js:32:5)
    at new Promise (<anonymous>)
    at promiseOrCallback (/app/node_modules/mongoose/lib/helpers/promiseOrCallback.js:31:10)
    at Mongoose._promiseOrCallback (/app/node_modules/mongoose/lib/index.js:1149:10)
    at Mongoose.connect (/app/node_modules/mongoose/lib/index.js:350:20)
    at exports.connect (/app/app/database/init.js:14:14)
    at /app/app.js:9:5
    at Object.<anonymous> (/app/app.js:11:3)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
message: "connect ECONNREFUSED 127.0.0.1:27017"
reason: {"type":"Single","setName":null,"maxSetVersion":null,"maxElectionId":null,"servers":{},"stale":false,"compatible":true,"compatibilityError":null,"logicalSessionTimeoutMinutes":null,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"commonWireVersion":null}
pid: 59
hostname: ef5539b3119b

